### ISSUE TITLE
Internal server error with PDF

### ISSUE THREAD

**Issue by dameert** [icapps/docker_qrdecode#1]
Hello,

I tested the following use case (imagine EUDCC):
- I have paper version of a qrcode that I want to pass to the docker image
- I used a scanner to generate a PDF with the qrcode (9MB file at 600dpi)
- The process uses 100% cpu, and around 21MB memory
- I receive an internal server error

Docker logs gives me the following
`Error: child exited with code 4
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/await-spawn/index.js:28:21)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  code: 4,
  stderr: BufferListStream {
    _bufs: [],
    length: 0,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    [Symbol(kCapture)]: false
  },
  stdout: BufferListStream {
    _bufs: [],
    length: 0,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    [Symbol(kCapture)]: false
  }
}`

I noticed that zbarimg rasterizes the pdf file automatically and might corrupt the qrcode in the pdf file?
http://manpages.ubuntu.com/manpages/bionic/man1/zbarimg.1.html

**Comment by jeroentrappers** [comment]
I've tested this: printed my EUDCC from eHealth, scanned to create a PDF. Resulting size is 1.5MB.

Process uses 100% cpu in short burst and 37MB memory.

Works as designed.

Can you provide the example file of 9MB?

**Comment by dameert** [comment]
Hello,

I found an image on the internet that is also not working:
https://itextpdf.com/sites/default/files/inline-images/Picture4.jpg

**Comment by jeroentrappers** [comment]
Quality of the image is insufficient. The caller should handle the error and ask the user to provide decent input.
