### ISSUE TITLE
Disabling logs

### ISSUE THREAD

**Issue by dameert** [icapps/docker_qrdecode#2]
The tool is logging its results to the console.
If a qr code would contain personal data, this might breach GDRP guidelines in certain contexts.

Would you be able to add an Environment Variable to the docker image that disables logging.

(optionally with different levels: no logs, error logs, all logs)

**Comment by jeroentrappers** [comment]
Just redirect the logs to /dev/null

**Comment by dameert** [comment]
> Just redirect the logs to /dev/null

Hello, will you modify the dockerfile to achieve this ?
