### ISSUE TITLE
> Just redirect the logs to /dev/null

### ISSUE THREAD

**Issue by dameert** [icapps/docker_qrdecode#3]
> Just redirect the logs to /dev/null

Hello, will you modify the dockerfile to achieve this ?

_Originally posted by @dameert in https://github.com/icapps/docker_qrdecode/issues/2#issuecomment-939948976_

Or could you remove line 50 in the server.js file ?
That line is logging GDPR sensitive information. The error logs are still usefull to us.

**Comment by jeroentrappers** [comment]
Line 50 removed.
